### ISSUE TITLE
Add more sponsors

### ISSUE THREAD

**Issue by aaarendt** [geo-smart/2023-hackweek-website#15]
We should acknowledge NSF and include the award number @NCristea. I will include the Cybertraining award I'm PI on.

**Comment by NCristea** [comment]
NSF CyberTraining |   | NSF #2117834

**Comment by aaarendt** [comment]
Anthony's CyberTraining award NSF #1829585

**Comment by aaarendt** [comment]
@friedrichknuth could you add an NSF logo and text with our two award numbers listed, at the bottom of the website? Thanks!
