### ISSUE TITLE
specify that the hackweek is hydrology and cryosphere focused

### ISSUE THREAD

**Issue by aaarendt** [geo-smart/2023-hackweek-website#19]
Somewhere on the splash page we need to be clear that the hackweek will have a domain focus on hydro and cryo. This will be important for applicants to see.

**Comment by friedrichknuth** [comment]
https://geosmart.hackweek.io/

Maybe change 

"GeoSmart Hackweek will focus primarily on project work, with project ideas shared in advance. There will be space for new ideas to emerge based on participant engagement. There will be about 5 hours of tutorials spread over the week, including space for participant-led tutorials."

to

"The 2023 GeoSmart Hackweek will focus primarily on project work, with an emphasis on applications in **Hydrology and Cyrosphere**. Project ideas will be shared in advance. There will be space for new ideas to emerge during the Hackweek based on participant engagement. We will provide about 5 hours of data science tutorials spread over the week, including space for participant-led tutorials."

**Comment by spestana** [comment]
There's also the sub-heading "Application of Machine Learning in the Geosciences."

Should that be changed to something like "Application of Machine Learning in Hydrology and Cryosphere Sciences." ?

**Comment by aaarendt** [comment]
Closed by #21
