### ISSUE TITLE
update JupyterBook

### ISSUE THREAD

**Issue by aaarendt** [geo-smart/2023-hackweek-website#8]
The current version of this hackweek's JupyterBook doesn't include some of the latest improvements we've made in the existing ICESat-2 2023 book around preliminary checklist and skills refreshers:

* [link to our new ICESat-2 material](https://icesat-2-2023.hackweek.io/preliminary/checklist_index.html)

In addition, the preliminary checklist needs to be modified to align with what we'll be doing in GeoSMART. E.g.:
* is Earthdata login needed (delete)?
* add info on connecting to hub (will it be hosted by HydroShare?)
* add login info for GeoWeaver?

(adding @spestana in case this is a task you might want to jump in on!)

**Comment by jomey** [comment]
This PR to the template contains all the required commits needing transfer to here to update to the 'Preliminary' section
https://github.com/uwhackweek/jupyterbook-template/pull/134
